CREATE TABLE `item` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `seller_id` bigint(20) DEFAULT NULL,
  `ISBN` varchar(45) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `press` varchar(255) DEFAULT NULL,
  `cover` varchar(255) DEFAULT NULL,
  `origin_price` double DEFAULT NULL,
  `price` double DEFAULT NULL,
  `description` text,
  `catalog_id` bigint(20) DEFAULT NULL,
  `father_catalog_id` bigint(20) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `dictionary` text,
  `delivery_type` int(11) DEFAULT NULL COMMENT '0为寄送， 1为当面交易，2都支持',
  `address` varchar(45) DEFAULT NULL,
  `state` int(11) DEFAULT NULL COMMENT '1为上架，2为下架，3为删除',
  `create_time` bigint(20) DEFAULT '0',
  `update_time` bigint(20) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_catolog` (`catalog_id`),
  KEY `idx_father_catlog` (`father_catalog_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8